"""Reviewed W07-W10 deltas, applied before older exact source contracts."""
CHANGES = {
  "iosApp/ZTransfer/Diagnostics/CameraHandshakeProbe.swift": [
    [
      "        task = Task {\n            defer {\n                running = false; task = nil; sessionReady = false\n                if productState?.phase != \"failed\" && productState?.phase != \"paired\" { publishProduct(\"idle\") }\n            }\n            do {\n                let address = host.trimmingCharacters(in: .whitespacesAndNewlines)\n",
      "        task = Task {\n            defer {\n                running = false; task = nil; sessionReady = false\n                if productState?.phase != \"failed\" { publishProduct(\"idle\") }\n            }\n            do {\n                let address = host.trimmingCharacters(in: .whitespacesAndNewlines)\n"
    ],
    [
      "                }\n            } catch {\n                status = Task.isCancelled ? \"诊断已取消，连接已关闭。\" : error.localizedDescription\n                if !Task.isCancelled, let station = error as? CameraStationError, case .pairingCompleted = station {\n                    publishProduct(\"paired\", message: error.localizedDescription)\n                } else {\n                    publishProduct(Task.isCancelled ? \"idle\" : \"failed\", message: Task.isCancelled ? nil : error.localizedDescription)\n                }\n            }\n        }\n    }\n",
      "                }\n            } catch {\n                status = Task.isCancelled ? \"诊断已取消，连接已关闭。\" : error.localizedDescription\n                publishProduct(Task.isCancelled ? \"idle\" : \"failed\", message: Task.isCancelled ? nil : error.localizedDescription)\n            }\n        }\n    }\n"
    ],
    [
      "            var readyMessage = description\n            if productState != nil {\n                let responder = await connection.responderGUID()\n                let resolvedHost = await connection.resolvedRemoteHost()\n                let historyState = await connection.snapshot()\n                try Task.checkCancellation()\n                guard historyState.phase == .ready, apConnection === connection,\n                      productState?.phase != \"closing\" else { throw CameraStreamError.closed }\n                do {\n                    try Self.recordVerifiedStationEndpoint(stationMode: stationMode, service: service, host: host,\n                        responderGUID: responder, displayName: description, resolvedHost: resolvedHost,\n                        history: CameraEndpointHistory.applicationStore)\n                } catch {\n                    readyMessage += \"（地址历史未保存：\\(error.localizedDescription)）\"\n                }\n",
      "            var readyMessage = description\n            if productState != nil {\n                let responder = await connection.responderGUID()\n                do {\n                    try Self.recordVerifiedStationEndpoint(stationMode: stationMode, service: service, host: host,\n                        responderGUID: responder, displayName: description, history: CameraEndpointHistory.applicationStore)\n                } catch {\n                    readyMessage += \"（地址历史未保存：\\(error.localizedDescription)）\"\n                }\n"
    ],
    [
      "    /// This history belongs to standard STA. An AP hotspot must not overwrite the same camera's\n    /// LAN address, and a Bonjour service name is never guessed to be a resolved host address.\n    nonisolated static func recordVerifiedStationEndpoint(stationMode: Bool, service: CameraBonjourService?, host: String,\n        responderGUID: String?, displayName: String, resolvedHost: String? = nil,\n        history: () throws -> CameraEndpointHistory) throws {\n        guard stationMode, let responderGUID, let address = service == nil ? host : resolvedHost else { return }\n        try history().recordSuccessful(responderGUID: responderGUID, displayName: displayName,\n            address: CameraEndpointAddress.parse(address))\n    }\n\n    private func receiveCatalogChange(_ snapshot: CameraCatalogSnapshot) {\n",
      "    /// This history belongs to standard STA. An AP hotspot must not overwrite the same camera's\n    /// LAN address, and a Bonjour service name is never guessed to be a resolved host address.\n    nonisolated static func recordVerifiedStationEndpoint(stationMode: Bool, service: CameraBonjourService?, host: String,\n        responderGUID: String?, displayName: String, history: () throws -> CameraEndpointHistory) throws {\n        guard stationMode, service == nil, let responderGUID else { return }\n        try history().recordSuccessful(responderGUID: responderGUID, displayName: displayName,\n                                       address: CameraEndpointAddress.parse(host))\n    }\n\n    private func receiveCatalogChange(_ snapshot: CameraCatalogSnapshot) {\n"
    ]
  ],
  "iosApp/ZTransfer/Network/CameraDiscoveryCoordinator.swift": [
    [
      "        reloadProfiles()\n    }\n    static func applicationCoordinator() throws -> CameraDiscoveryCoordinator {\n        try CameraDiscoveryCoordinator(history: CameraEndpointHistory.applicationDiscoveryStore(), profiles: StationProfileStore.applicationStore())\n    }\n    deinit { observer?.cancel(); discovery?.stop() }\n    func start() {\n",
      "        reloadProfiles()\n    }\n    static func applicationCoordinator() throws -> CameraDiscoveryCoordinator {\n        try CameraDiscoveryCoordinator(history: CameraEndpointHistory.applicationStore(), profiles: StationProfileStore.applicationStore())\n    }\n    deinit { observer?.cancel(); discovery?.stop() }\n    func start() {\n"
    ],
    [
      "        discovery?.stop(); discovery = nil; searching = false\n    }\n    func reloadProfiles() {\n        // Metadata and trust have independent failure domains. Corrupt address history must not\n        // hide a valid pairing identity; address-only rows never grant pairing authority.\n        var issues: [String] = []\n        var entries: [CameraEndpointRecord] = []\n        var paired = Set<String>()\n        do { entries = try history.entries() } catch { issues.append(error.localizedDescription) }\n        do { paired = Set(try profileStore.pairedResponderGUIDs()) } catch { issues.append(error.localizedDescription) }\n        profiles = entries.map { CameraKnownProfile(responderGUID: $0.responderGUID, displayName: $0.displayName,\n            address: $0.address.host, paired: paired.contains($0.responderGUID)) }\n        let represented = Set(entries.map(\\.responderGUID))\n        profiles += paired.subtracting(represented).sorted().map {\n            CameraKnownProfile(responderGUID: $0, displayName: \"已配对相机 · \\($0.suffix(8))\", address: nil, paired: true)\n        }\n        profileIssue = issues.isEmpty ? nil : issues.joined(separator: \"；\")\n        message = profileIssue\n    }\n    func selectService(id: String, expectedResponderGUID: String? = nil) -> CameraConnectionChoice? {\n        guard let service = selectableServices.first(where: { $0.id == id }) else { return nil }\n",
      "        discovery?.stop(); discovery = nil; searching = false\n    }\n    func reloadProfiles() {\n        do {\n            let entries = try history.entries()\n            let paired = Set(try profileStore.pairedResponderGUIDs())\n            profiles = entries.map { CameraKnownProfile(responderGUID: $0.responderGUID, displayName: $0.displayName,\n                address: $0.address.host, paired: paired.contains($0.responderGUID)) }\n            let represented = Set(entries.map(\\.responderGUID))\n            profiles += paired.subtracting(represented).sorted().map {\n                CameraKnownProfile(responderGUID: $0, displayName: \"已配对相机 · \\($0.suffix(8))\", address: nil, paired: true)\n            }\n            profileIssue = nil; message = nil\n        } catch { profiles = []; profileIssue = error.localizedDescription; message = profileIssue }\n    }\n    func selectService(id: String, expectedResponderGUID: String? = nil) -> CameraConnectionChoice? {\n        guard let service = selectableServices.first(where: { $0.id == id }) else { return nil }\n"
    ],
    [
      "        guard confirmed else { throw CameraEndpointError.confirmationRequired }\n        // Remove the trust marker first. A failed history write may leave a harmless address hint,\n        // but must never leave an allegedly-forgotten pairing trusted. Other identities are intact.\n        do {\n            try profileStore.forgetResponder(responderGUID)\n            try history.forget(responderGUID: responderGUID)\n        } catch {\n            reloadProfiles() // A failed metadata write must not display an already-removed trust marker.\n            throw error\n        }\n        reloadProfiles()\n    }\n    @discardableResult func resetHistoryAfterConfirmation(confirmed: Bool) throws -> URL? {\n",
      "        guard confirmed else { throw CameraEndpointError.confirmationRequired }\n        // Remove the trust marker first. A failed history write may leave a harmless address hint,\n        // but must never leave an allegedly-forgotten pairing trusted. Other identities are intact.\n        try profileStore.forgetResponder(responderGUID)\n        try history.forget(responderGUID: responderGUID)\n        reloadProfiles()\n    }\n    @discardableResult func resetHistoryAfterConfirmation(confirmed: Bool) throws -> URL? {\n"
    ]
  ],
  "iosApp/ZTransfer/Network/CameraEndpointHistory.swift": [
    [
      "    private static let diskLock = NSLock()\n    private let file: URL\n    private let now: () -> Int64\n    init(file: URL, validateOnOpen: Bool = true,\n         now: @escaping () -> Int64 = { Int64(Date().timeIntervalSince1970 * 1_000) }) throws {\n        guard file.isFileURL else { throw CameraEndpointError.corruptHistory }\n        self.file = file; self.now = now\n        Self.diskLock.lock(); defer { Self.diskLock.unlock() }\n        if validateOnOpen { _ = try Self.read(file) }\n    }\n    static func applicationStore() throws -> CameraEndpointHistory { try CameraEndpointHistory(file: applicationFile()) }\n    /// Discovery needs a handle even when metadata is damaged, so it can display valid identities\n    /// and offer explicit recovery. Every entries/select/write still validates the document.\n    static func applicationDiscoveryStore() throws -> CameraEndpointHistory {\n        try CameraEndpointHistory(file: applicationFile(), validateOnOpen: false)\n    }\n    private static func applicationFile() throws -> URL {\n        let support = try FileManager.default.url(for: .applicationSupportDirectory, in: .userDomainMask, appropriateFor: nil, create: true)\n        return support.appendingPathComponent(\"ZTransfer/camera-endpoint-history.json\")\n",
      "    private static let diskLock = NSLock()\n    private let file: URL\n    private let now: () -> Int64\n    init(file: URL, now: @escaping () -> Int64 = { Int64(Date().timeIntervalSince1970 * 1_000) }) throws {\n        guard file.isFileURL else { throw CameraEndpointError.corruptHistory }\n        self.file = file; self.now = now\n        Self.diskLock.lock(); defer { Self.diskLock.unlock() }\n        _ = try Self.read(file)\n    }\n    static func applicationStore() throws -> CameraEndpointHistory { try CameraEndpointHistory(file: applicationFile()) }\n    private static func applicationFile() throws -> URL {\n        let support = try FileManager.default.url(for: .applicationSupportDirectory, in: .userDomainMask, appropriateFor: nil, create: true)\n        return support.appendingPathComponent(\"ZTransfer/camera-endpoint-history.json\")\n"
    ]
  ],
  "iosApp/ZTransfer/Network/CameraTCPStream.swift": [
    [
      "\n/// This small Apple I/O seam also permits deterministic callback/short-read tests.\nprotocol CameraByteConnection: AnyObject {\n    func resolvedRemoteHost() -> String?\n    func start(on queue: DispatchQueue, state: @escaping (CameraConnectionEvent) -> Void)\n    func receive(maximumLength: Int, completion: @escaping (Data?, Bool, Error?) -> Void)\n    func send(_ data: Data, completion: @escaping (Error?) -> Void)\n    func cancel()\n}\n\nextension CameraByteConnection {\n    func resolvedRemoteHost() -> String? { nil } // Fixtures/non-Network transports provide no route evidence.\n}\n\nenum CameraConnectionEvent { case ready, failed(Error), cancelled }\n\nprivate final class AppleCameraByteConnection: CameraByteConnection {\n    private let connection: NWConnection\n    private let permittedInterface: Bool\n\n    func resolvedRemoteHost() -> String? {\n        guard case .ready = connection.state, let path = connection.currentPath,\n              CameraNetworkPathPolicy.failure(path) == nil else { return nil }\n        return CameraNetworkPathPolicy.numericRemoteHost(path.remoteEndpoint)\n    }\n\n    convenience init(host: String, port: UInt16) throws {\n        guard !host.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty,\n",
      "\n/// This small Apple I/O seam also permits deterministic callback/short-read tests.\nprotocol CameraByteConnection: AnyObject {\n    func start(on queue: DispatchQueue, state: @escaping (CameraConnectionEvent) -> Void)\n    func receive(maximumLength: Int, completion: @escaping (Data?, Bool, Error?) -> Void)\n    func send(_ data: Data, completion: @escaping (Error?) -> Void)\n    func cancel()\n}\n\nenum CameraConnectionEvent { case ready, failed(Error), cancelled }\n\nprivate final class AppleCameraByteConnection: CameraByteConnection {\n    private let connection: NWConnection\n\n    convenience init(host: String, port: UInt16) throws {\n        guard !host.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty,\n"
    ],
    [
      "        let parameters = NWParameters(tls: nil, tcp: tcp)\n        // Camera hotspots have no Internet: never fall back to cellular for this socket.\n        parameters.requiredInterfaceType = .wifi\n        if case .service(_, _, _, let interface) = endpoint, let interface {\n            parameters.requiredInterface = interface\n            permittedInterface = interface.type == .wifi\n        } else { permittedInterface = true }\n        connection = NWConnection(to: endpoint, using: parameters)\n    }\n\n    func start(on queue: DispatchQueue, state: @escaping (CameraConnectionEvent) -> Void) {\n        guard permittedInterface else { state(.failed(CameraStreamError.wifiUnavailable)); return }\n        var deliveredReady = false // Network callbacks are serialized on the supplied queue.\n        connection.pathUpdateHandler = { path in\n            guard deliveredReady, let failure = CameraNetworkPathPolicy.failure(path) else { return }\n            state(.failed(failure))\n        }\n        connection.stateUpdateHandler = { [weak self] update in\n            guard let self else { return }\n            switch update {\n            case .ready:\n                guard let path = self.connection.currentPath else { state(.failed(CameraStreamError.wifiUnavailable)); return }\n                if let failure = CameraNetworkPathPolicy.failure(path) { state(.failed(failure)); return }\n                deliveredReady = true\n                state(.ready)\n            case .waiting:\n                // Only explicit system evidence means denied. A prompt or timeout is not denial.\n                if self.connection.currentPath?.unsatisfiedReason == .localNetworkDenied {\n                    state(.failed(CameraStreamError.localNetworkDenied))\n                }\n            case .failed(let error):\n                if self.connection.currentPath?.unsatisfiedReason == .localNetworkDenied {\n                    state(.failed(CameraStreamError.localNetworkDenied))\n                } else { state(.failed(error)) }\n            case .cancelled: state(.cancelled)\n            // Waiting may include the Local Network prompt. A deadline bounds it but does not\n            // establish that the user denied permission.\n",
      "        let parameters = NWParameters(tls: nil, tcp: tcp)\n        // Camera hotspots have no Internet: never fall back to cellular for this socket.\n        parameters.requiredInterfaceType = .wifi\n        connection = NWConnection(to: endpoint, using: parameters)\n    }\n\n    func start(on queue: DispatchQueue, state: @escaping (CameraConnectionEvent) -> Void) {\n        connection.stateUpdateHandler = { update in\n            switch update {\n            case .ready: state(.ready)\n            case .failed(let error): state(.failed(error))\n            case .cancelled: state(.cancelled)\n            // Waiting may include the Local Network prompt. A deadline bounds it but does not\n            // establish that the user denied permission.\n"
    ],
    [
      "\n    func cancel() {\n        connection.stateUpdateHandler = nil\n        connection.pathUpdateHandler = nil\n        connection.cancel()\n    }\n}\n\nenum CameraStreamError: Error, LocalizedError, Equatable {\n    case invalidArgument, notConnected, operationInProgress, closed, timedOut, endOfStream\n    case wifiUnavailable, localNetworkDenied\n    var errorDescription: String? {\n        switch self {\n        case .wifiUnavailable: return \"相机 Wi-Fi 路由不可用，请在系统 Wi-Fi 设置中加入相机热点或与相机相同的局域网；不会改用蜂窝网络。\"\n        case .localNetworkDenied: return \"系统已禁止本应用访问局域网。请在应用系统设置中允许“本地网络”，返回后重新连接。\"\n        case .invalidArgument: return \"相机网络参数无效。\"\n        case .notConnected: return \"相机网络尚未连接。\"\n        case .operationInProgress: return \"相机通道正在执行同类操作。\"\n",
      "\n    func cancel() {\n        connection.stateUpdateHandler = nil\n        connection.cancel()\n    }\n}\n\nenum CameraStreamError: Error, LocalizedError, Equatable {\n    case invalidArgument, notConnected, operationInProgress, closed, timedOut, endOfStream\n    var errorDescription: String? {\n        switch self {\n        case .invalidArgument: return \"相机网络参数无效。\"\n        case .notConnected: return \"相机网络尚未连接。\"\n        case .operationInProgress: return \"相机通道正在执行同类操作。\"\n"
    ],
    [
      "        case .timedOut: return \"相机网络操作超时，请检查 Wi-Fi、相机状态和局域网权限。\"\n        case .endOfStream: return \"相机关闭了网络连接。\"\n        }\n    }\n}\n\n/// Apple transport evidence only, not camera authentication or Internet reachability.\nenum CameraNetworkPathPolicy {\n    static func numericRemoteHost(_ endpoint: NWEndpoint?) -> String? {\n        guard let endpoint, case .hostPort(let host, _) = endpoint else { return nil }\n        switch host {\n        case .ipv4, .ipv6: return try? CameraEndpointAddress.parse(String(describing: host)).host\n        default: return nil // Never turn an advertised name into a fabricated successful IP.\n        }\n    }\n    static func failure(_ path: NWPath) -> CameraStreamError? {\n        failure(satisfied: path.status == .satisfied, wifi: path.usesInterfaceType(.wifi),\n                denied: path.unsatisfiedReason == .localNetworkDenied)\n    }\n    static func failure(satisfied: Bool, wifi: Bool, denied: Bool) -> CameraStreamError? {\n        if denied { return .localNetworkDenied }\n        if !satisfied || !wifi { return .wifiUnavailable }\n        return nil\n    }\n}\n\n",
      "        case .timedOut: return \"相机网络操作超时，请检查 Wi-Fi、相机状态和局域网权限。\"\n        case .endOfStream: return \"相机关闭了网络连接。\"\n        }\n    }\n}\n\n"
    ],
    [
      "        self.init(connection: AppleCameraByteConnection(endpoint: service.endpoint))\n    }\n    init(connection: CameraByteConnection) { self.connection = connection }\n\n    func resolvedRemoteHost() async -> String? {\n        await withCheckedContinuation { continuation in\n            queue.async {\n                continuation.resume(returning: self.state == .ready ? self.connection.resolvedRemoteHost() : nil)\n            }\n        }\n    }\n\n    deinit { connection.cancel() }\n\n",
      "        self.init(connection: AppleCameraByteConnection(endpoint: service.endpoint))\n    }\n    init(connection: CameraByteConnection) { self.connection = connection }\n\n    deinit { connection.cancel() }\n\n"
    ]
  ],
  "iosApp/ZTransfer/Network/CameraWiFiConnection.swift": [
    [
      "    /// Pairing/history may use only the responder acknowledged by this ready session, never a\n    /// display name, Bonjour candidate or thumbnail-cache fallback containing a session UUID.\n    func responderGUID() -> String? { phase == .ready ? verifiedResponderGUID : nil }\n\n    func resolvedRemoteHost() async -> String? {\n        guard phase == .ready else { return nil }\n        let host = await command.resolvedRemoteHost()\n        return phase == .ready ? host : nil\n    }\n\n    private func initializeStation(options: StationConnectionOptions, responder: String?,\n                                   hasMarker: ((String) throws -> Bool)?, acknowledged: ((String) throws -> Void)?) async throws {\n",
      "    /// Pairing/history may use only the responder acknowledged by this ready session, never a\n    /// display name, Bonjour candidate or thumbnail-cache fallback containing a session UUID.\n    func responderGUID() -> String? { phase == .ready ? verifiedResponderGUID : nil }\n\n    private func initializeStation(options: StationConnectionOptions, responder: String?,\n                                   hasMarker: ((String) throws -> Bool)?, acknowledged: ((String) throws -> Void)?) async throws {\n"
    ]
  ],
  "iosApp/ZTransfer/Network/StationProfileStore.swift": [
    [
      "    var errorDescription: String? {\n        switch self {\n        case .unexpectedResponder: return \"响应相机与选中的机身身份不符，已停止连接。\"\n        case .pairingRequired: return \"相机需要完成电脑模式配对，请勾选“允许首次电脑模式配对”，重试并在相机端确认。\"\n        case .albumUnavailable: return \"STA 标准流程尚未取得可用相册；专用兼容/直接读取路径还未接入。\"\n        case .missingIdentity: return \"相机未返回可持久保存的机身身份，不能确认配对。\"\n        case .corruptIdentityStore: return \"本地相机身份文件无效；未重置身份或覆盖原文件。\"\n",
      "    var errorDescription: String? {\n        switch self {\n        case .unexpectedResponder: return \"响应相机与选中的机身身份不符，已停止连接。\"\n        case .pairingRequired: return \"相机需要完成电脑模式配对，请先启用配对诊断并在相机端确认。\"\n        case .albumUnavailable: return \"STA 标准流程尚未取得可用相册；专用兼容/直接读取路径还未接入。\"\n        case .missingIdentity: return \"相机未返回可持久保存的机身身份，不能确认配对。\"\n        case .corruptIdentityStore: return \"本地相机身份文件无效；未重置身份或覆盖原文件。\"\n"
    ],
    [
      "    }\n\n    private static func read(_ file: URL) throws -> Document {\n        let type = try file.resourceValues(forKeys: [.isRegularFileKey, .isSymbolicLinkKey])\n        guard type.isRegularFile == true, type.isSymbolicLink != true else { throw CameraStationError.corruptIdentityStore }\n        let length = try file.resourceValues(forKeys: [.fileSizeKey]).fileSize ?? 0\n        guard length <= 1024 * 1024 else { throw CameraStationError.corruptIdentityStore }\n        let document = try JSONDecoder().decode(Document.self, from: Data(contentsOf: file))\n",
      "    }\n\n    private static func read(_ file: URL) throws -> Document {\n        let length = try file.resourceValues(forKeys: [.fileSizeKey]).fileSize ?? 0\n        guard length <= 1024 * 1024 else { throw CameraStationError.corruptIdentityStore }\n        let document = try JSONDecoder().decode(Document.self, from: Data(contentsOf: file))\n"
    ]
  ],
  "iosApp/ZTransfer/UI/CameraWorkspace.swift": [
    [
      "    private var closed = false\n    private var pendingFilesNavigation = false\n    private var expectedResponderGUID: String?\n    private let connectionPreferences: CameraConnectionPreferences\n\n    init(session: CameraHandshakeProbe? = nil, connectionPreferences: CameraConnectionPreferences? = nil) {\n        self.session = session ?? CameraHandshakeProbe()\n        self.connectionPreferences = connectionPreferences ?? CameraConnectionPreferences()\n        super.init()\n        self.session.objectWillChange.sink { [weak self] _ in self?.objectWillChange.send() }.store(in: &observations)\n        self.session.$productState.sink { [weak self] value in\n",
      "    private var closed = false\n    private var pendingFilesNavigation = false\n    private var expectedResponderGUID: String?\n\n    init(session: CameraHandshakeProbe? = nil) {\n        self.session = session ?? CameraHandshakeProbe()\n        super.init()\n        self.session.objectWillChange.sink { [weak self] _ in self?.objectWillChange.send() }.store(in: &observations)\n        self.session.$productState.sink { [weak self] value in\n"
    ],
    [
      "        }.store(in: &observations)\n    }\n\n    func readConnectionMode() -> String? { connectionPreferences.read() }\n    func saveConnectionMode(stationMode: Bool) -> Bool { connectionPreferences.save(stationMode ? \"sta\" : \"ap\") }\n\n    func connectCamera(address: String, stationMode: Bool, allowPairing: Bool, requestId: Int64) -> Bool {\n        guard !closed else { return false }\n        guard let normalized = NativeCameraEndpointAddress.shared.normalize(raw: address) else {\n",
      "        }.store(in: &observations)\n    }\n\n    func connectCamera(address: String, stationMode: Bool, allowPairing: Bool, requestId: Int64) -> Bool {\n        guard !closed else { return false }\n        guard let normalized = NativeCameraEndpointAddress.shared.normalize(raw: address) else {\n"
    ],
    [
      "        pendingFilesNavigation = false\n        discovery?.stop(); discoveryObservation = nil\n        session.cancel(); observations.removeAll()\n    }\n}\n\n/// Presentation preference only. Never persist pairing permission, selected identity or a ready state.\n@MainActor final class CameraConnectionPreferences {\n    static let key = \"ztransfer.connection.preferences\"\n    private struct Document: Codable { let version: Int; let mode: String }\n    private let defaults: UserDefaults\n    init(defaults: UserDefaults = .standard) { self.defaults = defaults }\n    func read() -> String? {\n        guard let raw = defaults.object(forKey: Self.key) else { return \"ap\" }\n        guard let bytes = raw as? Data, bytes.count <= 4096,\n              let value = try? JSONDecoder().decode(Document.self, from: bytes),\n              value.version == 1, [\"ap\", \"sta\"].contains(value.mode) else { return nil }\n        return value.mode\n    }\n    func save(_ mode: String) -> Bool {\n        guard read() != nil, [\"ap\", \"sta\"].contains(mode),\n              let bytes = try? JSONEncoder().encode(Document(version: 1, mode: mode)) else { return false }\n        defaults.set(bytes, forKey: Self.key)\n        return defaults.data(forKey: Self.key) == bytes\n    }\n}\n\n",
      "        pendingFilesNavigation = false\n        discovery?.stop(); discoveryObservation = nil\n        session.cancel(); observations.removeAll()\n    }\n}\n\n"
    ]
  ]
}

def previous_connection_product_source(path, value):
    from transfer_completion_wiring import previous_transfer_completion_source
    value = previous_transfer_completion_source(path, value)
    for current, previous in CHANGES.get(path, ()):
        assert value.count(current) == 1, f"connection product hunk changed: {path}"
        value = value.replace(current, previous, 1)
    return value
