"""2026-09-10 user-requested queue layout fixes, applied AFTER the frozen migration oracle.

These exact substitutions authorize only action placement/popup hosting. Original task actions,
camera gating, removal order, animations and Android adapters are still checked byte-for-byte.
"""
def replace_once(source, old, new):
    if source.count(old) != 1:
        raise ValueError("Queue layout fix anchor changed: " + old[:80])
    return source.replace(old, new, 1)

PAGE_OLD = "                                Box(modifier = Modifier.weight(1f)) {\n                                    cardContent(task, displayedSpeed, displayedFrameGenerationElapsedMs, Modifier.fillMaxWidth())\n                                    SharedTransferRetryButton(\n                                        contentDescription = text.retry,\n                                        visible = cardActionsVisible &&\n                                            task.status == TransferStatus.FAILED,\n                                        enabled = cardActionsVisible &&\n                                            (connected || isOriginalTransferred(task)),\n                                        onClick = {\n                                            clearScope.launch(start = CoroutineStart.UNDISPATCHED) {\n                                                actions.retrySingleTask(taskId)\n                                            }\n                                        },\n                                        modifier = Modifier.align(Alignment.TopEnd),\n                                    )\n                                }"
PAGE_NEW = "                                Box(modifier = Modifier.weight(1f)) {\n                                    cardContent(task, displayedSpeed, displayedFrameGenerationElapsedMs, Modifier.fillMaxWidth())\n                                }\n\n                                // Both actions are children of the same vertically centered row.\n                                // Reserve a real column so retry cannot overlap wrapped error text.\n                                SharedTransferRetryButton(\n                                    contentDescription = text.retry,\n                                    visible = cardActionsVisible &&\n                                        task.status == TransferStatus.FAILED,\n                                    enabled = cardActionsVisible &&\n                                        (connected || isOriginalTransferred(task)),\n                                    onClick = {\n                                        clearScope.launch(start = CoroutineStart.UNDISPATCHED) {\n                                            actions.retrySingleTask(taskId)\n                                        }\n                                    },\n                                    modifier = Modifier.padding(start = 10.dp),\n                                )"
FAB_OLD = "    Column(horizontalAlignment = Alignment.End, modifier = modifier) {\n        AnimatedVisibility(\n            visible = expanded,\n            // 以右下角为原点缩放弹出，视觉上从 FAB 位置向左上方展开。\n            enter = scaleIn(transformOrigin = TransformOrigin(1f, 1f)) + fadeIn(),\n            exit = scaleOut(transformOrigin = TransformOrigin(1f, 1f)) + fadeOut()\n        ) {\n            ConfirmCard(\n                title = title,\n                subtitle = subtitle,\n                confirmText = confirmText,\n                confirmColor = confirmColor,\n                onConfirm = onConfirm,\n                onDismiss = onDismiss,\n                cancelText = cancelText,\n            )\n        }\n\n        Spacer(modifier = Modifier.height(12.dp))"
FAB_NEW = "    val confirmationVisibility = remember { MutableTransitionState(false) }\n    confirmationVisibility.targetState = expanded\n    Column(horizontalAlignment = Alignment.End, modifier = modifier) {\n        // A separate popup never contributes its measured height to the FAB stack.\n        // Keep it mounted during exit so dismissal retains the existing animation.\n        if (confirmationVisibility.currentState || confirmationVisibility.targetState) {\n            Popup(\n                popupPositionProvider = QueueConfirmationPositionProvider,\n                onDismissRequest = onDismiss,\n                properties = PopupProperties(focusable = true),\n            ) {\n                AnimatedVisibility(\n                    visibleState = confirmationVisibility,\n                    enter = scaleIn(transformOrigin = TransformOrigin(1f, 1f)) + fadeIn(),\n                    exit = scaleOut(transformOrigin = TransformOrigin(1f, 1f)) + fadeOut(),\n                ) {\n                    ConfirmCard(\n                        title = title,\n                        subtitle = subtitle,\n                        confirmText = confirmText,\n                        confirmColor = confirmColor,\n                        onConfirm = onConfirm,\n                        onDismiss = onDismiss,\n                        cancelText = cancelText,\n                    )\n                }\n            }\n        }\n\n        // Preserve the collapsed footprint and the 12dp gap above the button.\n        Spacer(modifier = Modifier.height(12.dp))"

def apply_page_fix(source):
    return replace_once(source, PAGE_OLD, PAGE_NEW)

def apply_cards_fix(source):
    source = replace_once(source, "import androidx.compose.ui.unit.dp",
        "import androidx.compose.ui.unit.dp\nimport androidx.compose.ui.window.Popup\nimport androidx.compose.ui.window.PopupProperties")
    source = replace_once(source,
        "            modifier = if (isFailed) Modifier.padding(end = 42.dp) else Modifier,",
        "            // Action buttons reserve their own space in the parent row.")
    return replace_once(source, FAB_OLD, FAB_NEW)

