// Generated from app/src/main/res/values*.*/strings.xml; do not hand translate.
import Foundation

enum AndroidLocalization {
    static let en: [String: String] = [
        "%1$d": "%1$d",
        "%1$d 分钟/天": "%1$d min/day",
        "%1$d 天": "%1$d days",
        "%1$d 张未能保存，原照片未受影响": "%1$d photos could not be saved. Originals are unchanged.",
        "%1$d/天": "%1$d/day",
        "%1$dMB/个": "%1$d MB each",
        "%1$s · %2$d 天高级版": "%1$s · %2$d-day Pro",
        "%1$s · 永久高级版": "%1$s · Lifetime Pro",
        "%1$s 到期": "Expires %1$s",
        "%1$s/年": "%1$s/yr",
        "%1$s，%2$s": "%1$s. %2$s",
        "1. 手机：开英文名热点（推荐 5 GHz": "1. Phone: start an English-named hotspot (5 GHz recommended",
        "1. 耗电管理 → 不限制": "1. Battery usage → Unrestricted",
        "1分钟": "1 min",
        "2. 多任务 → 锁定": "2. Recent apps → Lock",
        "2. 相机：设定菜单/网络菜单 → 连接到计算机 → 网络设定 → 创建配置文件 → 搜索 Wi-Fi 网络\\n3. 相机选择同一网络并输入密码，IP 选择“自动获得”，等待配置完成\\n4. 按 OK 进入“正在配对”界面\\n5. 在 App 中点击“连接相机”": "2. On the camera: Setup Menu/Network Menu → Connect to computer → Network settings → Create profile → Search for Wi-Fi network\\n3. On the camera, select the same network and enter its password; choose “Obtain automatically” for IP, then wait for setup to complete\\n4. Press OK to open the pairing screen\\n5. Tap “Connect Camera” in the app",
        "2分钟": "2 min",
        "30秒": "30 sec",
        "5 GHz 热点的信道由手机自动选择，可能选到相机不支持的信道。可到干扰较少的地方重开热点，或改用 2.4 GHz。仅切换频段无需重新配对，可放心修改。": "The phone chooses the 5 GHz hotspot channel automatically and may select one the camera does not support. Restart the hotspot where interference is lower, or use 2.4 GHz. Changing only the band does not require pairing again.",
        "5分钟": "5 min",
        "AP 模式不可用": "Unavailable in AP mode",
        "GPS": "GPS",
        "GPS 信号弱时，定位精度会下降，海拔可能显示 0 米，属于正常现象。": "With a weak GPS signal, accuracy may drop and altitude may show 0 m; this is normal.",
        "Logo": "Logo",
        "OpenSession 失败：%1$s": "OpenSession failed: %1$s",
        "PS：本模式对应相机中的 Wi-Fi AP 模式": "PS: This corresponds to the camera\\'s Wi-Fi AP mode",
        "STA 相机已断开，点击重新连接。": "STA camera disconnected. Tap to reconnect.",
        "STA 相机已连接": "STA camera connected",
        "STA 连接指引": "STA connection guide",
        "USB": "USB",
        "Wi-Fi": "Wi-Fi",
        "Wi-Fi 设置": "Wi-Fi Settings",
        "Z传": "ZTransfer",
        "Z传 v%1$s": "ZTransfer v%1$s",
        "Z传正在保持无线相机会话": "ZTransfer is keeping the wireless camera session active",
        "≈%1$s/月": "≈%1$s/month",
        "✓ 已保存到相册": "✓ Saved to album",
        "一年高级版": "Annual Pro",
        "一年高级版 · 微信扫码支付": "Annual Pro · Pay with WeChat",
        "下单失败，请稍后重试或联系客服。": "Couldn\\'t create the order — try again later or contact support.",
        "下载失败": "Download failed",
        "不可用": "No",
        "为了稳定运行，建议：": "For stable operation:",
        "事件握手失败": "Event channel handshake failed",
        "仅水印": "Watermark only",
        "仅高级版可用": "Available in Pro only",
        "今日剩余 %1$s": "%1$s left today",
        "今日剩余额度 %1$d/%2$d": "%1$d/%2$d left today",
        "今日监看时长已用完，解锁高级版不限时": "Daily remote time used up — unlock Pro for unlimited",
        "今日额度已用完，请解锁高级版": "Daily limit reached — unlock Pro",
        "从 i 菜单开启「Wi-Fi 连接」": "Start “Wi-Fi connection” from the i menu",
        "优先保存到原目录；不可写时自动保存到 Pictures/ZTransfer": "Saved beside the original, or to Pictures/ZTransfer when needed",
        "会话已打开": "Session already open",
        "会话未打开": "Session not open",
        "传完当前任务后暂停": "Pause after the current item",
        "传输": "Transfer",
        "传输原图后，效果图另存。": "After the original is transferred, the edited version is saved separately.",
        "传输失败": "Transfer failed",
        "传输失败：%1$s": "Transfer failed: %1$s",
        "传输完当前任务后将暂停": "Transfers will pause after the current item finishes",
        "传输已取消": "Transfer cancelled",
        "传输整组": "Transfer this group",
        "传输目录": "Transfer folder",
        "传输目录已失效，请重新选择": "Transfer folder is no longer valid. Please choose it again",
        "传输进行中，完成后再进入监看": "Transfer in progress — enter live view after it finishes",
        "传输进行中，监看可能卡顿": "Transfers in progress — live view may stutter",
        "位置": "Position",
        "你的激活码": "Your activation code",
        "使用 USB 数据线连接相机与手机": "Connect the camera and phone with a USB cable",
        "使相机拍照附带位置信息": "When enabled, photos taken with the camera include location information.",
        "保存到相册": "Save to album",
        "保存失败，请截图后到微信扫相册中的二维码付款": "Save failed — screenshot this code, then scan it from your album in WeChat",
        "保存失败：%1$s": "Save failed: %1$s",
        "保护": "Protected",
        "停止录制": "Stop recording",
        "免费": "Free",
        "免费版": "Free version",
        "全屏监看": "Fullscreen monitor",
        "全部": "All",
        "关闭": "Close",
        "其他": "Other",
        "再次返回退出": "Go back again to exit",
        "写入文件失败：%1$s": "Failed to write file: %1$s",
        "冷调日吻": "Cool Sun Kiss",
        "功能": "Feature",
        "加入传输队列后不会立即开始传输，方便继续预览挑选照片。": "Items added to the transfer queue do not start transferring immediately, so you can keep previewing and selecting photos.",
        "卡 %1$d": "Card %1$d",
        "原图传输": "Original transfers",
        "参数无效": "Invalid parameter",
        "反馈": "Feedback",
        "发现新版本": "Update available",
        "取消": "Cancel",
        "取消收藏当前效果": "Remove current effect from favorites",
        "可多选照片，共用当前滤镜、边框和水印，效果图另存。": "Select multiple photos to apply the same filter, frame, and watermark. Edited photos are saved as new copies.",
        "可将「Wi-Fi 连接」加入相机的 i 菜单，之后按 i 键即可快速开启。": "Add “Wi-Fi connection” to the camera\\'s i menu, then press i to turn it on quickly.",
        "可读性": "Legibility",
        "和煦": "Soft Harmony",
        "品牌": "Brand",
        "品牌内嵌": "Brand Inset",
        "品牌留白": "Brand Gallery",
        "回到顶部": "Back to top",
        "固件错误 (0x%1$s)": "Firmware error (0x%1$s)",
        "图内·中上": "Photo top center",
        "图内·中下": "Photo bottom center",
        "图内·中央": "Photo center",
        "图内·右上": "Photo top right",
        "图内·右下": "Photo bottom right",
        "图内·左上": "Photo top left",
        "图内·左下": "Photo bottom left",
        "在上方页面完成支付，到账后自动激活。": "Complete the payment above — activation is automatic once confirmed.",
        "在新设备输入此激活码即可换机，本机会恢复成免费版。请勿滥用，滥用会导致激活码失效。": "Enter this code on the new device to switch — this one reverts to Free. Don\\'t misuse it: misuse disables the code.",
        "地址": "Address",
        "型号": "Model",
        "城市绿意": "Urban Green",
        "墨绿暗影": "Green Shadows",
        "复制": "Copy",
        "复制不完整 %1$d/%2$d": "Copy incomplete %1$d/%2$d",
        "复制支付链接（在电脑浏览器打开即显示二维码）": "Copy payment link (open on a computer to show the QR)",
        "复制日志": "Copy log",
        "复古活力": "Vintage Vibe",
        "夕照柔光": "Sunset Glow",
        "外观": "Appearance",
        "大小": "Size",
        "大小：%1$s": "Size: %1$s",
        "天空薄雾": "Sky Mist",
        "字体": "Font",
        "存储不可用": "Storage unavailable",
        "存储卡": "Storage card",
        "存储已满": "Storage full",
        "安装": "Install",
        "安装包版本不匹配，已删除": "Update version mismatch. File deleted.",
        "完成": "Done",
        "完整探测": "Probe",
        "实时传输": "Real-time transfer",
        "客服": "Support",
        "将在当前任务完成后暂停": "Will pause after the current item",
        "将忘记此 App 已配对的所有相机，之后需要在相机中重新创建“连接到计算机”配置并重新配对。": "This app will forget all paired cameras. Recreate the “Connect to computer” profile on each camera, then pair again.",
        "将清除已保存的相机身份，下次使用时需要重新配对。": "The saved camera identity will be removed. Pair again next time.",
        "尝试过于频繁，请一分钟后再试": "Too many attempts — try again in a minute",
        "屏幕常亮": "Keep screen on",
        "展开": "Expand",
        "已保存": "Saved",
        "已保存 %1$d 张": "Saved %1$d photos",
        "已保存 %1$d/%2$d 张": "Saved %1$d/%2$d photos",
        "已保存到：%1$s": "Saved to: %1$s",
        "已全部加入队列": "All added to queue",
        "已加入队列": "Already in queue",
        "已取消": "Cancelled",
        "已复制": "Copied",
        "已复制 QQ 号 %1$s\\n请加 QQ 反馈": "QQ %1$s copied\\nAdd on QQ to send feedback",
        "已复制客服 QQ：%1$s": "Support QQ %1$s copied",
        "已复制支付链接": "Payment link copied",
        "已复制激活码": "Activation code copied",
        "已恢复为免费版（测试）": "Reverted to free (testing)",
        "已收到付款但自动激活未成功，请复制上方激活码，用「输入激活码」完成激活。": "Payment received but auto-activation failed — copy the code above and use \"Enter activation code\".",
        "已是最新版本": "Up to date",
        "已激活": "Activated",
        "已设置": "Folder selected",
        "已配对": "Paired",
        "已配对 %1$d 台相机": "Paired cameras: %1$d",
        "帧率显示": "FPS overlay",
        "年": "Year",
        "开发者": "Developer",
        "开发者工具": "Developer tools",
        "开启": "Enabled",
        "开启GPS": "Enable GPS",
        "开启蓝牙": "Turn on Bluetooth",
        "开启蓝牙与定位服务": "Turn on Bluetooth and Location",
        "开始": "Start",
        "开始传输": "Start transfers",
        "强度 %1$d%%": "Intensity %1$d%%",
        "录制": "Record",
        "录制失败": "Recording failed",
        "录制已保存": "Recording saved",
        "录制监看画面": "Record live view",
        "微信扫码支付后，回到 Z传 自动激活": "After paying with WeChat, return to ZTransfer for automatic activation",
        "必须更新": "Update required",
        "忽略此版本": "Ignore this version",
        "恋爱柔光": "Love Glow",
        "恢复录制": "Resume recording",
        "我要换机": "Switch device",
        "手机": "Phone",
        "手机 Wi-Fi 连接到相机的热点": "Connect your phone\\'s Wi-Fi to the camera\\'s hotspot",
        "打开下载页": "Open download page",
        "打开支付页面": "Open payment page",
        "打开相机配对": "Camera pairing",
        "找不到已保存的原片，请先重新传输": "The saved original could not be found. Transfer it again first.",
        "拍摄日期": "Date taken",
        "指定的对象不存在": "Object does not exist",
        "按天保存": "Save by day",
        "按拍摄日期分文件夹保存；关闭后直接保存到传输目录。": "Save files in folders by capture date. When off, save them directly in the transfer folder.",
        "按钮风格": "Button style",
        "换机或重装时需要此激活码，请妥善保存。": "Keep this activation code safe. You\\'ll need it when switching devices or reinstalling.",
        "授权": "License",
        "描边": "Outline",
        "握手失败：空响应": "Handshake failed: empty response",
        "握手失败：非 ACK 响应": "Handshake failed: unexpected response",
        "操作不支持": "Operation not supported",
        "支付二维码加载失败，请重试，不要重复付款。": "The payment QR code could not be loaded. Please retry, and do not pay twice.",
        "支付已超时": "Payment timed out",
        "支持": "Supported",
        "收藏当前效果": "Add current effect to favorites",
        "收起": "Collapse",
        "效果图水印": "Effect watermarks",
        "效果图滤镜": "Effect filters",
        "效果图边框": "Effect frames",
        "数据不完整：收到 %1$d / 预期 %2$d 字节": "Incomplete data: received %1$d of %2$d bytes",
        "文件传输": "File transfer",
        "文件保护": "File is protected",
        "文件大小": "File size",
        "文件类型": "File type",
        "文字": "Text",
        "斑马纹": "Zebra stripes",
        "旋转屏幕": "Rotate screen",
        "旋转照片": "Rotate photo",
        "无水印": "No watermark",
        "无法停止录像，请检查相机后重试": "Couldn\\'t stop recording — check the camera and try again",
        "无法创建文件": "Couldn\\'t create file",
        "无法导入这个 Logo": "Couldn’t import this logo",
        "无法开始录像": "Couldn\\'t start recording",
        "无法打开安装器": "Couldn\\'t open installer",
        "无法打开文件": "Couldn\\'t open file",
        "无法确认本单金额，已停止支付。请重试。": "The order total could not be verified. Payment was stopped; please retry.",
        "无法读取相机照片信息，请重试": "Could not read photo details from the camera. Please retry.",
        "无法连接服务器。若当前连着相机 Wi-Fi，请先断开，用有外网的网络重试。": "Couldn\\'t reach the server. If you\\'re on the camera\\'s Wi-Fi, disconnect first and retry on a network with internet access.",
        "无法连接激活服务器，请检查网络；若网络正常，可能需要更新到新版本（QQ 群获取）。": "Couldn\\'t reach the activation server. Check your network; if the network is fine, update to the latest version (via QQ group).",
        "无法连接相机": "Could not connect to camera",
        "无滤镜": "No filter",
        "无线相机已连接": "Wireless camera connected",
        "无限": "Unlimited",
        "无预览": "No preview",
        "无麦克风权限，录制无声音": "No microphone permission — recording without sound",
        "日": "Day",
        "日期": "Date",
        "日期格式": "Date format",
        "日期范围": "Date range",
        "旧日色彩": "Vintage Color",
        "时效": "Duration",
        "时间格式": "Time format",
        "明暗": "Light & dark",
        "晨曦": "Dawn Hues",
        "智能": "Auto",
        "暂停录制": "Pause recording",
        "暂时无法获取地点名称，请稍后重试": "Couldn’t find a place name. Try again later.",
        "暖夜微光": "Warm Lowlight",
        "暖白": "Warm white",
        "暖秋": "Cozy Autumn",
        "暖街": "Warm Street",
        "暖调人像": "Warm Portrait",
        "暖阳亲吻": "Warm Sun Kiss",
        "暗夜": "Cinema",
        "暗房胶片": "Darkroom Film",
        "暮色余温": "Dusk Ember",
        "曝光参数": "Exposure",
        "更快的连接方式": "A faster way to connect",
        "更换 Logo": "Replace logo",
        "更换图片": "Replace photo",
        "更改目录": "Change folder",
        "月": "Month",
        "有线连接已断开": "USB connection lost",
        "木纹": "Wood",
        "未传": "Pending",
        "未开放": "Unavailable",
        "未找到兼容相机，请检查相机的网络配置与连接状态。": "No compatible camera found. Check the camera network profile and connection.",
        "未找到相机": "Camera not found",
        "未指定对象": "No object specified",
        "未检测到相机": "Camera not detected",
        "未知 USB 错误": "Unknown USB error",
        "未知日期": "Unknown date",
        "未获得 USB 权限，请重新插线并允许访问": "USB permission was not granted. Reconnect the cable and allow access.",
        "未设置": "Not set",
        "松石蓝": "Turquoise Blue",
        "构图参考线": "Framing grid",
        "柔光": "Soft Glow",
        "柔暖人像": "Soft Portrait",
        "柠黄负片": "Lemon Negative",
        "检查中…": "Checking…",
        "检查失败，请检查网络": "Check failed. Check your network.",
        "检查更新": "Check for updates",
        "森屿青": "Forest Verdure",
        "正在下载…": "Downloading…",
        "正在下载… %1$d%%": "Downloading… %1$d%%",
        "正在传输文件…": "Transferring files…",
        "正在创建订单…": "Creating order…",
        "正在加载更多…": "Loading more…",
        "正在寻找": "Searching",
        "正在尝试重连": "Trying to reconnect",
        "正在打开支付宝…": "Opening Alipay…",
        "正在查询地点…": "Finding the place name…",
        "正在校验…": "Verifying…",
        "正在生成…": "Generating…",
        "正在生成支付二维码…": "Generating payment QR…",
        "正在获取下载链接…": "Getting download link…",
        "正在获取文件列表…": "Loading file list…",
        "正在识别相机…": "Identifying camera…",
        "正在连接": "Connecting",
        "正在配对": "Pairing",
        "正在重新连接…": "Reconnecting…",
        "每行数量": "Items per row",
        "毛玻璃": "Frosted Glass",
        "水印": "Watermark",
        "水印类型": "Watermark type",
        "水印设置": "Watermark settings",
        "水印：%1$s": "Watermark: %1$s",
        "水平仪": "Level",
        "永久": "Lifetime",
        "永久版": "Lifetime",
        "永久版暂未开放": "Lifetime plan unavailable",
        "永久高级版": "Lifetime Pro",
        "永久高级版 · 微信扫码支付": "Lifetime Pro · Pay with WeChat",
        "沉浸": "Immersive",
        "没有符合筛选的照片": "No photos match the filter",
        "波轮：按住上下拖动可快速调节": "Wheels: Hold and drag vertically for quick adjustments",
        "流畅签名": "Flowing signature",
        "浅色": "Light",
        "海拔": "Altitude",
        "海拔：%1$d 米": "Altitude: %1$d m",
        "深色": "Dark",
        "清柔": "Gentle Clarity",
        "清空": "Clear",
        "清空队列": "Clear queue",
        "清空队列？": "Clear the queue?",
        "清透人像": "Clear Portrait",
        "清除 GPS 配对": "Clear GPS pairing",
        "清除 GPS 配对？": "Clear GPS pairing?",
        "清除筛选": "Clear filters",
        "滤镜·边框·水印": "Filter · Frame · Watermark",
        "滤镜强度": "Intensity",
        "滤镜：%1$s · %2$d%%": "Filter: %1$s · %2$d%%",
        "漂白银盐": "Bleached Silver",
        "激活": "Activate",
        "激活中…": "Activating…",
        "激活失败（%1$s）": "Activation failed (%1$s)",
        "激活失败，请联系客服": "Activation failed. Please contact support.",
        "激活成功，感谢支持！": "Activated — thank you!",
        "激活时会将设备标识发送至激活服务器，仅用于授权验证。": "Activation sends this device\\'s identifier to the activation server, used only for license verification.",
        "激活码不存在": "Activation code not found",
        "濑户蓝": "Setouchi Blue",
        "点击 连接相机": "Connect button",
        "点击：传输\\n长按：预览": "Tap: transfer\\nHold: preview",
        "点击：预览\\n长按：传输": "Tap: preview\\nHold: transfer",
        "热点设置": "Hotspot",
        "焦距": "Focal",
        "照片列表操作": "Photo list actions",
        "照片效果说明": "About photo effects",
        "照片滤镜": "Photo filter",
        "照片直方图": "Photo histogram",
        "父对象不存在": "Parent object does not exist",
        "版本 %1$s": "Version %1$s",
        "状态": "Status",
        "玫瑰旧片": "Rose Vintage",
        "玫瑰棕": "Rosewood",
        "琥珀负片": "Amber Negative",
        "生成 %1$s": "Generation %1$s",
        "生成中": "Generating",
        "生成失败": "Generation failed",
        "生成失败，原照片未受影响": "Couldn’t generate the photo. The original is unchanged.",
        "生成并保存": "Generate and save",
        "生成并保存（%1$d）": "Generate and save (%1$d)",
        "生成效果图": "Generate effect images",
        "电影暮影": "Cinematic Dusk",
        "电影蓝": "Cinema Blue",
        "界面皮肤": "UI Skin",
        "监看\\n遥控": "Live\\nRemote",
        "监看直方图": "Live view histogram",
        "相机": "Camera",
        "相机中没有照片": "No photos on the camera",
        "相机存储卡内未检测到照片或视频，请先拍摄内容后重试。": "No photos or videos were returned by the camera. Capture something to the memory card, then try again.",
        "相机尚未就绪，请保持开机，稍后将自动重连。": "Camera is not ready yet. Keep it powered on; reconnection will retry automatically.",
        "相机已配对": "Camera paired",
        "相机开启「与智能设备建立 Wi-Fi 连接」": "On the camera, enable “Connect to smart device (Wi-Fi)”",
        "相机拒绝连接": "Camera refused connection",
        "相机拒绝连接，请重新配对。": "Camera refused the connection. Pair the camera again.",
        "相机按键": "Camera Buttons",
        "相机无线连接": "Wireless camera connection",
        "相机未连接": "Camera not connected",
        "相机热点": "Camera hotspot",
        "相机电源开启": "Keep the camera powered on",
        "相机电量": "Camera battery",
        "相机监看": "Camera live view",
        "相机请按 OK": "Press OK on camera",
        "相机连接中断，重连后重试可续传": "Camera connection lost — retry to resume after reconnecting",
        "相机连接到手机发起的热点": "Connect the camera to the phone’s personal hotspot",
        "石墨": "Graphite",
        "移出队列": "Remove from queue",
        "移除全部卡片；正在传输的不受影响": "Removes all cards; the file currently transferring is not affected",
        "稍后": "Later",
        "窄体铭牌": "Condensed plaque",
        "立即更新": "Update now",
        "立即购买": "Buy Now",
        "端侧录制是高级版功能": "On-device recording is a Pro feature",
        "等待": "Waiting",
        "筛选": "Filter",
        "筛选类型": "Filter by type",
        "简白": "Minimal",
        "简约": "Simple",
        "粉彩柔光": "Pastel Pink",
        "系统拒绝改名与复制": "System refused to rename or copy the file",
        "红青负片": "Red Cyan",
        "经典签名": "Classic Signature",
        "经典胶片": "Classic Film",
        "经纬度": "Coordinates",
        "结束": "End",
        "续费": "Renew",
        "续费成功 · 有效期延长至 %1$s": "Renewed · Valid until %1$s",
        "续费或升级": "Renew or upgrade",
        "编辑照片效果": "Edit photo effects",
        "编辑衬线": "Editorial serif",
        "胶片画廊": "Film Gallery",
        "胶片边框": "Film Edge",
        "自动": "Auto",
        "自动 ISO": "Auto ISO",
        "自然联结": "Natural Link",
        "自由定制": "Custom",
        "自适应": "Adaptive",
        "色彩档案": "Color Archive",
        "艺术装裱": "Gallery Mat",
        "苔绿情绪": "Moss Mood",
        "英伦黑白": "British Mono",
        "茶青负片": "Teal Negative",
        "获取下载链接失败": "Couldn\\'t get download link",
        "菜单 → 自定义设定菜单 → 控制 → 自定义 i 菜单 → 选个顺手的格子 → Wi-Fi 连接": "MENU → Custom Settings Menu → Controls → Customize i menu → pick a slot → Wi-Fi connection",
        "落日胶片": "Sunset Film",
        "蓝色记忆": "Blue Memory",
        "蓝调时刻": "Blue Hour",
        "蕨影": "Fern Shade",
        "蜜糖暖调": "Honey Warm",
        "规范不兼容": "Incompatible specification",
        "视频暂不支持播放": "Video playback isn’t supported yet",
        "解锁": "Unlock",
        "解锁高级版": "Unlock Pro",
        "触感反馈": "Haptic feedback",
        "订阅已到期，请续费后继续使用": "Subscription expired — renew to continue",
        "设备固件错误": "Camera firmware error",
        "设备忙": "Camera busy",
        "设备码 %1$s": "Device code %1$s",
        "设备错误 (0x%1$s)": "Device error (0x%1$s)",
        "设置": "Settings",
        "设置说明": "Settings guide",
        "该激活码已被停用": "This activation code has been revoked",
        "语言": "Language",
        "请保存到相册后，用微信扫码支付": "Save to your album, then scan with WeChat to pay",
        "请允许蓝牙和定位权限": "Allow Bluetooth and location to enable GPS",
        "请先关闭 GPS": "Turn off GPS before connecting",
        "请先设置传输目录": "Please set a transfer folder first",
        "请先选择当前水印图片，再使用这个收藏": "Choose a current watermark image before using this favorite",
        "请将相机切换到自动区域 AF 或主体跟踪 AF 后重试": "Use Auto-area AF or Subject-tracking AF on the camera, then try again",
        "请将相机切换到自动对焦后使用点按对焦": "Switch the camera to autofocus to use tap focus",
        "请手动更新，已复制到剪贴板": "Update manually. Copied to clipboard",
        "请打开手机蓝牙以开启 GPS": "Turn on Bluetooth to enable GPS",
        "请打开相机电源": "Please turn on the camera",
        "请打开相机电源并检查 USB 数据线": "Turn on the camera and check the USB cable",
        "请断开相机 Wi-Fi": "Disconnect the camera Wi-Fi first",
        "请检查相机连接状态": "Check the camera connection",
        "请设置传输目录": "Set a transfer folder",
        "请连接相机 Wi-Fi": "Connect to the camera\\'s Wi-Fi",
        "请选择保存在本机相册中且可写入的照片": "Choose a writable photo stored on this phone",
        "请重新开启相机 Wi-Fi": "Restart the camera\\'s Wi-Fi",
        "读取相机信息失败：%1$s": "Could not read camera information: %1$s",
        "购买一年高级版 · %1$s · %2$d 天": "Buy Annual Pro · %1$s · %2$d days",
        "购买前请断开相机热点，连接互联网后重试。": "Disconnect the camera hotspot before purchasing, then connect to the internet and retry.",
        "购买永久高级版 · %1$s · 永久": "Buy Lifetime Pro · %1$s · Lifetime",
        "超过 %1$d MB，请解锁高级版": "Over %1$d MB — unlock Pro",
        "超过 4 GB": "Over 4 GB",
        "跳过": "Skipped",
        "轻柔胶片": "Soft Film",
        "输入激活码": "Enter code",
        "边框": "Frame",
        "边框·右侧": "Frame right",
        "边框·居中": "Frame center",
        "边框·左侧": "Frame left",
        "边框·随样式": "Frame auto",
        "边框与水印": "Frame & watermark",
        "边框与水印预览": "Frame and watermark preview",
        "边框信息": "Frame info",
        "边框和水印": "Frame & watermark",
        "边框：%1$s": "Frame: %1$s",
        "边框：截图等无 EXIF 的图片不显示拍摄参数": "Frame: Images without EXIF data, such as screenshots, won’t show shooting details",
        "返回": "Back",
        "返回选择方案": "Back to plans",
        "这张照片暂时无法预览，可滑动查看其他照片": "Preview unavailable. Swipe to view other photos.",
        "连拍": "Burst",
        "连拍会显示成合集状态，防止刷屏。": "Burst photos appear as a collection so they do not flood the list.",
        "连拍合集，共 %1$d 张": "Burst collection, %1$d photos",
        "连拍成组": "Group bursts",
        "连接失败": "Connection failed",
        "连接已中断": "Connection interrupted",
        "连接已断开": "Connection lost",
        "连接成功": "Connected",
        "连接期间新增的照片和视频会自动加入传输列表。": "Photos and videos added while connected appear in the transfer list automatically.",
        "连接相机": "Connect",
        "连接至智能设备 → 配对 → 开始配对": "Connect to smart device → Pairing → Start pairing",
        "追踪探测开始后，让有纹理的主体位于画面中央并缓慢移动": "When tracking probe starts, keep a textured subject near center and move it slowly",
        "退出全屏": "Exit fullscreen",
        "选完再传": "Transfer after selecting",
        "选择图片": "Choose photo",
        "选择目录": "Choose folder",
        "透明度": "Opacity",
        "通用错误 (0x%1$s)": "General error (0x%1$s)",
        "通知权限用于保活，不会有其他通知，可放心开启。": "Notification access keeps ZTransfer running. No other notifications will be sent, so you can safely enable it.",
        "遥控": "Remote",
        "遥控 · 监看": "Remote control",
        "醒目": "Bold",
        "重新发起支付": "Start payment again",
        "重新选择": "Choose again",
        "重置": "Reset",
        "重置 STA 配对？": "Reset STA pairing?",
        "重试": "Retry",
        "重试失败任务": "Retry failed tasks",
        "重试失败任务？": "Retry failed tasks?",
        "金色黄昏": "Golden Dusk",
        "钛合金": "Titanium",
        "铭牌": "Plaque",
        "错误 (0x%1$s)": "Error (0x%1$s)",
        "镜头型号": "Lens",
        "长按关闭": "Hold to stop",
        "长按滤镜拨轮可按分类选择": "Hold the photo filter wheel to choose by category",
        "长期免费": "Always free",
        "阴影": "Shadow",
        "限时特惠": "Limited-time offer",
        "雾白": "Mist",
        "雾蓝哑光": "Matte Blue",
        "雾霾蓝": "Mist blue",
        "青橙电影": "Teal and Orange",
        "青色负片": "Cyan Negative",
        "静谧微风": "Calm Breeze",
        "非法包长度 %1$d：连接数据已损坏": "Invalid packet length %1$d: connection data corrupted",
        "音频电平": "Audio levels",
        "预览暂时不可用": "Preview temporarily unavailable",
        "预览：左右滑动切换照片 · 长按对比滤镜前后": "Preview: Swipe between photos · Hold to compare with the unfiltered version",
        "预览：点击放大 · 双击旋转 · 长按对比滤镜前后": "Preview: Tap to enlarge · Double-tap to rotate · Hold to compare",
        "频率": "Update frequency",
        "颜色": "Color",
        "首次:": "First:",
        "首次连接": "First connection",
        "香槟金": "Champagne",
        "高清监看 (XGA)": "XGA live view",
        "高级版": "Pro",
        "高级版已到期": "Pro has expired",
        "高级版已解锁": "Pro unlocked",
        "高级版授权已过期，请连接网络后重开 App 自动续期。": "Pro license expired — connect to the internet and reopen to renew automatically.",
        "高级版支持换机，妥善保存激活码即可": "Pro supports switching devices · Keep your activation code safe",
        "鲜活胶片": "Vital Film",
        "黄绿负片": "Lime Negative",
        "默认": "Default",
        "默认水印": "Default",
        "（可多选）": "(Select multiple photos)",
        "）或连现有 Wi-Fi": ") or join an existing Wi-Fi network",
    ]
    static let hant: [String: String] = [
        "%1$d": "%1$d",
        "%1$d 分钟/天": "%1$d 分鐘/天",
        "%1$d 天": "%1$d 天",
        "%1$d 张未能保存，原照片未受影响": "%1$d 張未能儲存，原照片未受影響",
        "%1$d/天": "%1$d/天",
        "%1$dMB/个": "%1$dMB/個",
        "%1$s · %2$d 天高级版": "%1$s · %2$d 天高級版",
        "%1$s · 永久高级版": "%1$s · 永久高級版",
        "%1$s 到期": "%1$s 到期",
        "%1$s/年": "%1$s/年",
        "%1$s，%2$s": "%1$s，%2$s",
        "1. 手机：开英文名热点（推荐 5 GHz": "1. 手機：開英文名熱點（建議 5 GHz",
        "1. 耗电管理 → 不限制": "1. 耗電管理 → 不限制",
        "1分钟": "1 分鐘",
        "2. 多任务 → 锁定": "2. 多工 → 鎖定",
        "2. 相机：设定菜单/网络菜单 → 连接到计算机 → 网络设定 → 创建配置文件 → 搜索 Wi-Fi 网络\\n3. 相机选择同一网络并输入密码，IP 选择“自动获得”，等待配置完成\\n4. 按 OK 进入“正在配对”界面\\n5. 在 App 中点击“连接相机”": "2. 相機：設定選單/網路選單 → 連接至電腦 → 網路設定 → 建立設定檔 → 搜尋 Wi-Fi 網路\\n3. 相機選擇同一網路並輸入密碼，IP 選擇「自動獲得」，等待設定完成\\n4. 按 OK 進入「正在配對」畫面\\n5. 在 App 中點擊「連接相機」",
        "2分钟": "2 分鐘",
        "30秒": "30 秒",
        "5 GHz 热点的信道由手机自动选择，可能选到相机不支持的信道。可到干扰较少的地方重开热点，或改用 2.4 GHz。仅切换频段无需重新配对，可放心修改。": "5 GHz 熱點的頻道由手機自動選擇，可能選到相機不支援的頻道。可到干擾較少的地方重開熱點，或改用 2.4 GHz。僅切換頻段無需重新配對，可放心修改。",
        "5分钟": "5 分鐘",
        "AP 模式不可用": "AP 模式不可用",
        "GPS": "GPS",
        "GPS 信号弱时，定位精度会下降，海拔可能显示 0 米，属于正常现象。": "GPS 訊號較弱時，定位精度會下降，海拔可能顯示 0 公尺，屬於正常現象。",
        "Logo": "Logo",
        "OpenSession 失败：%1$s": "OpenSession 失敗：%1$s",
        "PS：本模式对应相机中的 Wi-Fi AP 模式": "PS：本模式對應相機中的 Wi-Fi AP 模式",
        "STA 相机已断开，点击重新连接。": "STA 相機已斷線，點擊重新連線。",
        "STA 相机已连接": "STA 相機已連線",
        "STA 连接指引": "STA 連線指引",
        "USB": "USB",
        "Wi-Fi": "Wi-Fi",
        "Wi-Fi 设置": "Wi-Fi 設定",
        "Z传": "Z傳",
        "Z传 v%1$s": "Z傳 v%1$s",
        "Z传正在保持无线相机会话": "Z傳正在保持無線相機工作階段",
        "≈%1$s/月": "≈%1$s/月",
        "✓ 已保存到相册": "✓ 已儲存到相簿",
        "一年高级版": "一年高級版",
        "一年高级版 · 微信扫码支付": "一年高級版 · 微信掃碼付款",
        "下单失败，请稍后重试或联系客服。": "下單失敗，請稍後重試或聯絡客服。",
        "下载失败": "下載失敗",
        "不可用": "不可用",
        "为了稳定运行，建议：": "為了穩定運行，建議：",
        "事件握手失败": "事件交握失敗",
        "仅水印": "僅浮水印",
        "仅高级版可用": "僅高級版可用",
        "今日剩余 %1$s": "今日剩餘 %1$s",
        "今日剩余额度 %1$d/%2$d": "今日剩餘額度 %1$d/%2$d",
        "今日监看时长已用完，解锁高级版不限时": "今日監看時長已用完，解鎖高級版不限時",
        "今日额度已用完，请解锁高级版": "今日額度已用完，請解鎖高級版",
        "从 i 菜单开启「Wi-Fi 连接」": "從 i 選單開啟「Wi-Fi 連線」",
        "优先保存到原目录；不可写时自动保存到 Pictures/ZTransfer": "優先儲存到原目錄；無法寫入時自動儲存到 Pictures/ZTransfer",
        "会话已打开": "工作階段已開啟",
        "会话未打开": "工作階段未開啟",
        "传完当前任务后暂停": "傳完目前任務後暫停",
        "传输": "傳輸",
        "传输原图后，效果图另存。": "傳輸原圖後，效果圖另存。",
        "传输失败": "傳輸失敗",
        "传输失败：%1$s": "傳輸失敗：%1$s",
        "传输完当前任务后将暂停": "傳輸完目前任務後將暫停",
        "传输已取消": "傳輸已取消",
        "传输整组": "傳輸整組",
        "传输目录": "傳輸目錄",
        "传输目录已失效，请重新选择": "傳輸目錄已失效，請重新選擇",
        "传输进行中，完成后再进入监看": "傳輸進行中，完成後再進入監看",
        "传输进行中，监看可能卡顿": "傳輸進行中，監看可能卡頓",
        "位置": "位置",
        "你的激活码": "你的啟用碼",
        "使用 USB 数据线连接相机与手机": "使用 USB 資料線連接相機與手機",
        "使相机拍照附带位置信息": "使相機拍照附帶位置資訊",
        "保存到相册": "儲存到相簿",
        "保存失败，请截图后到微信扫相册中的二维码付款": "儲存失敗，請截圖後到微信掃相簿中的二維碼付款",
        "保存失败：%1$s": "儲存失敗：%1$s",
        "保护": "保護",
        "停止录制": "停止錄製",
        "免费": "免費",
        "免费版": "免費版",
        "全屏监看": "全螢幕監看",
        "全部": "全部",
        "关闭": "關閉",
        "其他": "其他",
        "再次返回退出": "再次返回離開",
        "写入文件失败：%1$s": "寫入檔案失敗：%1$s",
        "冷调日吻": "冷調日吻",
        "功能": "功能",
        "加入传输队列后不会立即开始传输，方便继续预览挑选照片。": "加入傳輸佇列後不會立即開始傳輸，方便繼續預覽挑選照片。",
        "卡 %1$d": "卡 %1$d",
        "原图传输": "原圖傳輸",
        "参数无效": "參數無效",
        "反馈": "回饋",
        "发现新版本": "發現新版本",
        "取消": "取消",
        "取消收藏当前效果": "取消收藏目前效果",
        "可多选照片，共用当前滤镜、边框和水印，效果图另存。": "可多選照片，共用目前濾鏡、邊框和浮水印，效果圖另存。",
        "可将「Wi-Fi 连接」加入相机的 i 菜单，之后按 i 键即可快速开启。": "可將「Wi-Fi 連線」加入相機的 i 選單，之後按 i 鍵即可快速開啟。",
        "可读性": "易讀性",
        "和煦": "和煦",
        "品牌": "品牌",
        "品牌内嵌": "品牌內嵌",
        "品牌留白": "品牌留白",
        "回到顶部": "回到頂部",
        "固件错误 (0x%1$s)": "韌體錯誤 (0x%1$s)",
        "图内·中上": "圖內·中上",
        "图内·中下": "圖內·中下",
        "图内·中央": "圖內·中央",
        "图内·右上": "圖內·右上",
        "图内·右下": "圖內·右下",
        "图内·左上": "圖內·左上",
        "图内·左下": "圖內·左下",
        "在上方页面完成支付，到账后自动激活。": "在上方頁面完成付款，到帳後自動啟用。",
        "在新设备输入此激活码即可换机，本机会恢复成免费版。请勿滥用，滥用会导致激活码失效。": "在新裝置輸入此啟用碼即可換機，本機會恢復成免費版。請勿濫用，濫用會導致啟用碼失效。",
        "地址": "地址",
        "型号": "型號",
        "城市绿意": "城市綠意",
        "墨绿暗影": "墨綠暗影",
        "复制": "複製",
        "复制不完整 %1$d/%2$d": "複製不完整 %1$d/%2$d",
        "复制支付链接（在电脑浏览器打开即显示二维码）": "複製支付連結（在電腦瀏覽器開啟即顯示二維碼）",
        "复制日志": "複製日誌",
        "复古活力": "復古活力",
        "夕照柔光": "夕照柔光",
        "外观": "外觀",
        "大小": "大小",
        "大小：%1$s": "大小：%1$s",
        "天空薄雾": "天空薄霧",
        "字体": "字型",
        "存储不可用": "儲存空間不可用",
        "存储卡": "記憶卡",
        "存储已满": "儲存空間已滿",
        "安装": "安裝",
        "安装包版本不匹配，已删除": "安裝套件版本不相符，已刪除",
        "完成": "完成",
        "完整探测": "完整探測",
        "实时传输": "即時傳輸",
        "客服": "客服",
        "将在当前任务完成后暂停": "將在目前任務完成後暫停",
        "将忘记此 App 已配对的所有相机，之后需要在相机中重新创建“连接到计算机”配置并重新配对。": "將忘記此 App 已配對的所有相機，之後需要在相機中重新建立「連接至電腦」設定檔並重新配對。",
        "将清除已保存的相机身份，下次使用时需要重新配对。": "將清除已儲存的相機身分，下次使用時需要重新配對。",
        "尝试过于频繁，请一分钟后再试": "嘗試過於頻繁，請一分鐘後再試",
        "屏幕常亮": "保持螢幕開啟",
        "展开": "展開",
        "已保存": "已儲存",
        "已保存 %1$d 张": "已儲存 %1$d 張",
        "已保存 %1$d/%2$d 张": "已儲存 %1$d/%2$d 張",
        "已保存到：%1$s": "已儲存至：%1$s",
        "已全部加入队列": "已全部加入佇列",
        "已加入队列": "已加入佇列",
        "已取消": "已取消",
        "已复制": "已複製",
        "已复制 QQ 号 %1$s\\n请加 QQ 反馈": "已複製 QQ 號 %1$s\\n請加 QQ 回饋",
        "已复制客服 QQ：%1$s": "已複製客服 QQ：%1$s",
        "已复制支付链接": "已複製支付連結",
        "已复制激活码": "已複製啟用碼",
        "已恢复为免费版（测试）": "已恢復為免費版（測試）",
        "已收到付款但自动激活未成功，请复制上方激活码，用「输入激活码」完成激活。": "已收到付款但自動啟用未成功，請複製上方啟用碼，用「輸入啟用碼」完成啟用。",
        "已是最新版本": "已是最新版本",
        "已激活": "已啟用",
        "已设置": "已設定",
        "已配对": "已配對",
        "已配对 %1$d 台相机": "已配對 %1$d 台相機",
        "帧率显示": "幀率顯示",
        "年": "年",
        "开发者": "開發者",
        "开发者工具": "開發者工具",
        "开启": "開啟",
        "开启GPS": "開啟GPS",
        "开启蓝牙": "開啟藍牙",
        "开启蓝牙与定位服务": "開啟藍牙與定位服務",
        "开始": "開始",
        "开始传输": "開始傳輸",
        "强度 %1$d%%": "強度 %1$d%%",
        "录制": "錄製",
        "录制失败": "錄製失敗",
        "录制已保存": "錄製已儲存",
        "录制监看画面": "錄製監看畫面",
        "微信扫码支付后，回到 Z传 自动激活": "微信掃碼付款後，返回 Z傳 自動啟用",
        "必须更新": "必須更新",
        "忽略此版本": "忽略此版本",
        "恋爱柔光": "戀愛柔光",
        "恢复录制": "恢復錄製",
        "我要换机": "我要換機",
        "手机": "手機",
        "手机 Wi-Fi 连接到相机的热点": "手機 Wi-Fi 連線到相機的熱點",
        "打开下载页": "開啟下載頁",
        "打开支付页面": "開啟支付頁面",
        "打开相机配对": "開啟相機配對",
        "找不到已保存的原片，请先重新传输": "找不到已儲存的原片，請先重新傳輸",
        "拍摄日期": "拍攝日期",
        "指定的对象不存在": "指定的物件不存在",
        "按天保存": "按天儲存",
        "按拍摄日期分文件夹保存；关闭后直接保存到传输目录。": "依拍攝日期分資料夾儲存；關閉後直接儲存到傳輸目錄。",
        "按钮风格": "按鈕風格",
        "换机或重装时需要此激活码，请妥善保存。": "換機或重新安裝時需要此啟用碼，請妥善保存。",
        "授权": "授權",
        "描边": "描邊",
        "握手失败：空响应": "交握失敗：空回應",
        "握手失败：非 ACK 响应": "交握失敗：非 ACK 回應",
        "操作不支持": "操作不支援",
        "支付二维码加载失败，请重试，不要重复付款。": "付款二維碼載入失敗，請重試，不要重複付款。",
        "支付已超时": "付款已逾時",
        "支持": "支援",
        "收藏当前效果": "收藏目前效果",
        "收起": "收起",
        "效果图水印": "效果圖浮水印",
        "效果图滤镜": "效果圖濾鏡",
        "效果图边框": "效果圖邊框",
        "数据不完整：收到 %1$d / 预期 %2$d 字节": "資料不完整：收到 %1$d / 預期 %2$d 位元組",
        "文件传输": "檔案傳輸",
        "文件保护": "檔案受保護",
        "文件大小": "檔案大小",
        "文件类型": "檔案類型",
        "文字": "文字",
        "斑马纹": "斑馬紋",
        "旋转屏幕": "旋轉螢幕",
        "旋转照片": "旋轉照片",
        "无水印": "無浮水印",
        "无法停止录像，请检查相机后重试": "無法停止錄影，請檢查相機後重試",
        "无法创建文件": "無法建立檔案",
        "无法导入这个 Logo": "無法匯入這個 Logo",
        "无法开始录像": "無法開始錄影",
        "无法打开安装器": "無法開啟安裝程式",
        "无法打开文件": "無法開啟檔案",
        "无法确认本单金额，已停止支付。请重试。": "無法確認本單金額，已停止付款。請重試。",
        "无法读取相机照片信息，请重试": "無法讀取相機照片資訊，請重試",
        "无法连接服务器。若当前连着相机 Wi-Fi，请先断开，用有外网的网络重试。": "無法連接伺服器。若目前連著相機 Wi-Fi，請先斷開，改用有外網的網路重試。",
        "无法连接激活服务器，请检查网络；若网络正常，可能需要更新到新版本（QQ 群获取）。": "無法連接啟用伺服器，請檢查網路；若網路正常，可能需要更新到新版本（QQ 群取得）。",
        "无法连接相机": "無法連接相機",
        "无滤镜": "無濾鏡",
        "无线相机已连接": "無線相機已連線",
        "无限": "無限",
        "无预览": "無預覽",
        "无麦克风权限，录制无声音": "無麥克風權限，錄製無聲音",
        "日": "日",
        "日期": "日期",
        "日期格式": "日期格式",
        "日期范围": "日期範圍",
        "旧日色彩": "舊日色彩",
        "时效": "時效",
        "时间格式": "時間格式",
        "明暗": "明暗",
        "晨曦": "晨曦",
        "智能": "智慧",
        "暂停录制": "暫停錄製",
        "暂时无法获取地点名称，请稍后重试": "暫時無法取得地點名稱，請稍後重試",
        "暖夜微光": "暖夜微光",
        "暖白": "暖白",
        "暖秋": "暖秋",
        "暖街": "暖街",
        "暖调人像": "暖調人像",
        "暖阳亲吻": "暖陽親吻",
        "暗夜": "暗夜",
        "暗房胶片": "暗房底片",
        "暮色余温": "暮色餘溫",
        "曝光参数": "曝光參數",
        "更快的连接方式": "更快的連線方式",
        "更换 Logo": "更換 Logo",
        "更换图片": "更換圖片",
        "更改目录": "變更目錄",
        "月": "月",
        "有线连接已断开": "有線連線已中斷",
        "木纹": "木紋",
        "未传": "未傳",
        "未开放": "未開放",
        "未找到兼容相机，请检查相机的网络配置与连接状态。": "找不到相容相機，請檢查相機的網路設定與連線狀態。",
        "未找到相机": "找不到相機",
        "未指定对象": "未指定物件",
        "未检测到相机": "未偵測到相機",
        "未知 USB 错误": "未知 USB 錯誤",
        "未知日期": "未知日期",
        "未获得 USB 权限，请重新插线并允许访问": "未取得 USB 權限，請重新插線並允許存取",
        "未设置": "未設定",
        "松石蓝": "松石藍",
        "构图参考线": "構圖參考線",
        "柔光": "柔光",
        "柔暖人像": "柔暖人像",
        "柠黄负片": "檸黃負片",
        "检查中…": "檢查中…",
        "检查失败，请检查网络": "檢查失敗，請檢查網路",
        "检查更新": "檢查更新",
        "森屿青": "森嶼青",
        "正在下载…": "正在下載…",
        "正在下载… %1$d%%": "正在下載… %1$d%%",
        "正在传输文件…": "正在傳輸檔案…",
        "正在创建订单…": "正在建立訂單…",
        "正在加载更多…": "正在載入更多…",
        "正在寻找": "正在尋找",
        "正在尝试重连": "正在嘗試重新連線",
        "正在打开支付宝…": "正在開啟支付寶…",
        "正在查询地点…": "正在查詢地點…",
        "正在校验…": "正在驗證…",
        "正在生成…": "正在產生…",
        "正在生成支付二维码…": "正在產生支付二維碼…",
        "正在获取下载链接…": "正在取得下載連結…",
        "正在获取文件列表…": "正在取得檔案清單…",
        "正在识别相机…": "正在辨識相機…",
        "正在连接": "正在連線",
        "正在配对": "正在配對",
        "正在重新连接…": "正在重新連接…",
        "每行数量": "每行數量",
        "毛玻璃": "毛玻璃",
        "水印": "浮水印",
        "水印类型": "浮水印類型",
        "水印设置": "浮水印設定",
        "水印：%1$s": "浮水印：%1$s",
        "水平仪": "水平儀",
        "永久": "永久",
        "永久版": "永久版",
        "永久版暂未开放": "永久版暫未開放",
        "永久高级版": "永久高級版",
        "永久高级版 · 微信扫码支付": "永久高級版 · 微信掃碼付款",
        "沉浸": "沉浸",
        "没有符合筛选的照片": "沒有符合篩選的照片",
        "波轮：按住上下拖动可快速调节": "撥輪：按住上下拖動可快速調整",
        "流畅签名": "流暢簽名",
        "浅色": "淺色",
        "海拔": "海拔",
        "海拔：%1$d 米": "海拔：%1$d 公尺",
        "深色": "深色",
        "清柔": "清柔",
        "清空": "清空",
        "清空队列": "清空佇列",
        "清空队列？": "清空佇列？",
        "清透人像": "清透人像",
        "清除 GPS 配对": "清除 GPS 配對",
        "清除 GPS 配对？": "清除 GPS 配對？",
        "清除筛选": "清除篩選",
        "滤镜·边框·水印": "濾鏡·邊框·浮水印",
        "滤镜强度": "濾鏡強度",
        "滤镜：%1$s · %2$d%%": "濾鏡：%1$s · %2$d%%",
        "漂白银盐": "漂白銀鹽",
        "激活": "啟用",
        "激活中…": "啟用中…",
        "激活失败（%1$s）": "啟用失敗（%1$s）",
        "激活失败，请联系客服": "啟用失敗，請聯絡客服",
        "激活成功，感谢支持！": "啟用成功，感謝支持！",
        "激活时会将设备标识发送至激活服务器，仅用于授权验证。": "啟用時會將裝置識別碼傳送至啟用伺服器，僅用於授權驗證。",
        "激活码不存在": "啟用碼不存在",
        "濑户蓝": "瀨戶藍",
        "点击 连接相机": "點擊 連接相機",
        "点击：传输\\n长按：预览": "點擊：傳輸\\n長按：預覽",
        "点击：预览\\n长按：传输": "點擊：預覽\\n長按：傳輸",
        "热点设置": "熱點設定",
        "焦距": "焦距",
        "照片列表操作": "照片列表操作",
        "照片效果说明": "照片效果說明",
        "照片滤镜": "照片濾鏡",
        "照片直方图": "照片直方圖",
        "父对象不存在": "父物件不存在",
        "版本 %1$s": "版本 %1$s",
        "状态": "狀態",
        "玫瑰旧片": "玫瑰舊片",
        "玫瑰棕": "玫瑰棕",
        "琥珀负片": "琥珀負片",
        "生成 %1$s": "產生 %1$s",
        "生成中": "產生中",
        "生成失败": "產生失敗",
        "生成失败，原照片未受影响": "產生失敗，原照片未受影響",
        "生成并保存": "產生並儲存",
        "生成并保存（%1$d）": "產生並儲存（%1$d）",
        "生成效果图": "產生效果圖",
        "电影暮影": "電影暮影",
        "电影蓝": "電影藍",
        "界面皮肤": "介面皮膚",
        "监看\\n遥控": "監看\\n遙控",
        "监看直方图": "監看直方圖",
        "相机": "相機",
        "相机中没有照片": "相機中沒有照片",
        "相机存储卡内未检测到照片或视频，请先拍摄内容后重试。": "相機記憶卡內未偵測到相片或影片，請先拍攝內容後重試。",
        "相机尚未就绪，请保持开机，稍后将自动重连。": "相機尚未就緒，請保持開機，稍後將自動重新連線。",
        "相机已配对": "相機已配對",
        "相机开启「与智能设备建立 Wi-Fi 连接」": "相機開啟「與智慧裝置建立 Wi-Fi 連線」",
        "相机拒绝连接": "相機拒絕連接",
        "相机拒绝连接，请重新配对。": "相機拒絕連線，請重新配對。",
        "相机按键": "相機按鍵",
        "相机无线连接": "相機無線連線",
        "相机未连接": "相機未連線",
        "相机热点": "相機熱點",
        "相机电源开启": "相機電源開啟",
        "相机电量": "相機電量",
        "相机监看": "相機監看",
        "相机请按 OK": "相機請按 OK",
        "相机连接中断，重连后重试可续传": "相機連線中斷，重連後重試可續傳",
        "相机连接到手机发起的热点": "相機連接到手機開啟的熱點",
        "石墨": "石墨",
        "移出队列": "移出佇列",
        "移除全部卡片；正在传输的不受影响": "移除全部卡片；正在傳輸的不受影響",
        "稍后": "稍後",
        "窄体铭牌": "窄體銘牌",
        "立即更新": "立即更新",
        "立即购买": "立即購買",
        "端侧录制是高级版功能": "端側錄製是高級版功能",
        "等待": "等待",
        "筛选": "篩選",
        "筛选类型": "篩選類型",
        "简白": "簡白",
        "简约": "簡約",
        "粉彩柔光": "粉彩柔光",
        "系统拒绝改名与复制": "系統拒絕重新命名與複製",
        "红青负片": "紅青負片",
        "经典胶片": "經典底片",
        "经纬度": "經緯度",
        "结束": "結束",
        "续费": "續費",
        "续费成功 · 有效期延长至 %1$s": "續費成功 · 有效期延長至 %1$s",
        "续费或升级": "續費或升級",
        "编辑照片效果": "編輯照片效果",
        "编辑衬线": "編輯襯線",
        "自动": "自動",
        "自动 ISO": "自動 ISO",
        "自然联结": "自然聯結",
        "自由定制": "自由自訂",
        "自适应": "自適應",
        "色彩档案": "色彩檔案",
        "苔绿情绪": "苔綠情緒",
        "英伦黑白": "英倫黑白",
        "茶青负片": "茶青負片",
        "获取下载链接失败": "取得下載連結失敗",
        "菜单 → 自定义设定菜单 → 控制 → 自定义 i 菜单 → 选个顺手的格子 → Wi-Fi 连接": "選單 → 自訂設定選單 → 控制 → 自訂 i 選單 → 選個順手的格子 → Wi-Fi 連線",
        "落日胶片": "落日底片",
        "蓝色记忆": "藍色記憶",
        "蓝调时刻": "藍調時刻",
        "蕨影": "蕨影",
        "蜜糖暖调": "蜜糖暖調",
        "规范不兼容": "規格不相容",
        "视频暂不支持播放": "影片暫不支援播放",
        "解锁": "解鎖",
        "解锁高级版": "解鎖高級版",
        "触感反馈": "觸覺回饋",
        "订阅已到期，请续费后继续使用": "訂閱已到期，請續費後繼續使用",
        "设备固件错误": "裝置韌體錯誤",
        "设备忙": "裝置忙碌",
        "设备码 %1$s": "裝置碼 %1$s",
        "设备错误 (0x%1$s)": "裝置錯誤 (0x%1$s)",
        "设置": "設定",
        "设置说明": "設定說明",
        "该激活码已被停用": "該啟用碼已被停用",
        "语言": "語言",
        "请保存到相册后，用微信扫码支付": "請儲存到相簿後，用微信掃碼付款",
        "请允许蓝牙和定位权限": "請允許藍牙和定位權限",
        "请先关闭 GPS": "請先關閉 GPS",
        "请先设置传输目录": "請先設定傳輸目錄",
        "请先选择当前水印图片，再使用这个收藏": "請先選擇目前的浮水印圖片，再使用這個收藏",
        "请将相机切换到自动区域 AF 或主体跟踪 AF 后重试": "請將相機切換到自動區域 AF 或主體追蹤 AF 後重試",
        "请将相机切换到自动对焦后使用点按对焦": "請將相機切換到自動對焦後使用點按對焦",
        "请手动更新，已复制到剪贴板": "請手動更新，已複製到剪貼簿",
        "请打开手机蓝牙以开启 GPS": "請開啟手機藍牙以啟用 GPS",
        "请打开相机电源": "請開啟相機電源",
        "请打开相机电源并检查 USB 数据线": "請開啟相機電源並檢查 USB 資料線",
        "请断开相机 Wi-Fi": "請中斷相機 Wi-Fi",
        "请检查相机连接状态": "請檢查相機連接狀態",
        "请设置传输目录": "請設定傳輸目錄",
        "请连接相机 Wi-Fi": "請連線至相機 Wi-Fi",
        "请选择保存在本机相册中且可写入的照片": "請選擇儲存在本機相簿中且可寫入的照片",
        "请重新开启相机 Wi-Fi": "請重新開啟相機 Wi-Fi",
        "读取相机信息失败：%1$s": "讀取相機資訊失敗：%1$s",
        "购买一年高级版 · %1$s · %2$d 天": "購買一年高級版 · %1$s · %2$d 天",
        "购买前请断开相机热点，连接互联网后重试。": "請先連接網際網路",
        "购买永久高级版 · %1$s · 永久": "購買永久高級版 · %1$s · 永久",
        "超过 %1$d MB，请解锁高级版": "超過 %1$d MB，請解鎖高級版",
        "超过 4 GB": "超過 4 GB",
        "跳过": "跳過",
        "轻柔胶片": "輕柔底片",
        "输入激活码": "輸入啟用碼",
        "边框": "邊框",
        "边框·右侧": "邊框·右側",
        "边框·居中": "邊框·置中",
        "边框·左侧": "邊框·左側",
        "边框·随样式": "邊框·隨樣式",
        "边框与水印": "邊框與浮水印",
        "边框与水印预览": "邊框與浮水印預覽",
        "边框信息": "邊框資訊",
        "边框和水印": "邊框和浮水印",
        "边框：%1$s": "邊框：%1$s",
        "边框：截图等无 EXIF 的图片不显示拍摄参数": "邊框：截圖等無 EXIF 的圖片不顯示拍攝參數",
        "返回": "返回",
        "返回选择方案": "返回選擇方案",
        "这张照片暂时无法预览，可滑动查看其他照片": "這張照片暫時無法預覽，可滑動查看其他照片",
        "连拍": "連拍",
        "连拍会显示成合集状态，防止刷屏。": "連拍會以合集狀態顯示，防止洗版。",
        "连拍合集，共 %1$d 张": "連拍合集，共 %1$d 張",
        "连拍成组": "連拍成組",
        "连接失败": "連接失敗",
        "连接已中断": "連接已中斷",
        "连接已断开": "連線已中斷",
        "连接成功": "連線成功",
        "连接期间新增的照片和视频会自动加入传输列表。": "連線期間新增的照片和影片會自動加入傳輸清單。",
        "连接相机": "連接相機",
        "连接至智能设备 → 配对 → 开始配对": "連線至智慧型裝置 → 配對 → 開始配對",
        "追踪探测开始后，让有纹理的主体位于画面中央并缓慢移动": "追蹤探測開始後，讓有紋理的主體位於畫面中央並緩慢移動",
        "退出全屏": "退出全螢幕",
        "选完再传": "選完再傳",
        "选择图片": "選擇圖片",
        "选择目录": "選擇目錄",
        "透明度": "透明度",
        "通用错误 (0x%1$s)": "一般錯誤 (0x%1$s)",
        "通知权限用于保活，不会有其他通知，可放心开启。": "通知權限用於保活，不會有其他通知，可放心開啟。",
        "遥控": "遙控",
        "遥控 · 监看": "遙控 · 監看",
        "醒目": "醒目",
        "重新发起支付": "重新發起付款",
        "重新选择": "重新選擇",
        "重置": "重設",
        "重置 STA 配对？": "重設 STA 配對？",
        "重试": "重試",
        "重试失败任务": "重試失敗任務",
        "重试失败任务？": "重試失敗任務？",
        "金色黄昏": "金色黃昏",
        "钛合金": "鈦合金",
        "铭牌": "銘牌",
        "错误 (0x%1$s)": "錯誤 (0x%1$s)",
        "镜头型号": "鏡頭型號",
        "长按关闭": "長按關閉",
        "长按滤镜拨轮可按分类选择": "長按濾鏡撥輪可按分類選擇",
        "长期免费": "長期免費",
        "阴影": "陰影",
        "限时特惠": "限時特惠",
        "雾白": "霧白",
        "雾蓝哑光": "霧藍霧面",
        "雾霾蓝": "霧霾藍",
        "青橙电影": "青橙電影",
        "青色负片": "青色負片",
        "静谧微风": "靜謐微風",
        "非法包长度 %1$d：连接数据已损坏": "非法封包長度 %1$d：連線資料已損壞",
        "音频电平": "音訊電平",
        "预览暂时不可用": "預覽暫時無法使用",
        "预览：左右滑动切换照片 · 长按对比滤镜前后": "預覽：左右滑動切換照片 · 長按對比濾鏡前後",
        "预览：点击放大 · 双击旋转 · 长按对比滤镜前后": "預覽：點擊放大 · 雙擊旋轉 · 長按對比濾鏡前後",
        "频率": "頻率",
        "颜色": "顏色",
        "首次:": "首次:",
        "首次连接": "首次連線",
        "香槟金": "香檳金",
        "高清监看 (XGA)": "高清監看 (XGA)",
        "高级版": "高級版",
        "高级版已到期": "高級版已到期",
        "高级版已解锁": "高級版已解鎖",
        "高级版授权已过期，请连接网络后重开 App 自动续期。": "高級版授權已過期，請連接網路後重開 App 自動續期。",
        "高级版支持换机，妥善保存激活码即可": "高級版支援換機，妥善保存啟用碼即可",
        "鲜活胶片": "鮮活底片",
        "黄绿负片": "黃綠負片",
        "默认": "預設",
        "默认水印": "預設浮水印",
        "（可多选）": "（可多選）",
        "）或连现有 Wi-Fi": "）或連現有 Wi-Fi",
    ]
}
